### ISSUE TITLE
Publish the book somewhere

### ISSUE THREAD

**Issue by pierd** [datprotocol/book#2]
This a 🙋 feature request.

It would be nice to make the book available online in built form.

## Possible Solution - GitHub Pages
One solution would be to use GitHub Pages. According to [docs](https://help.github.com/articles/user-organization-and-project-pages/#project-pages-sites) we could use the approach of having the book built into `/docs` directory on the `master` branch.

It can be build like this:
```
$ mdbook build -d docs
```

And once `docs` directory is checked into `master` it can be made available under [https://datrs.github.io/book](https://datrs.github.io/book).

**Comment by yoshuawuyts** [comment]
Another option might be [netlify](https://www.netlify.com/) which has cool things like team support. But I'm thinking perhaps even better might be to setup a travis script that can build and publish to GH pages (e.g. `gh-pages` branch).

I reckon that should be mostly straight forward after we check in the credentials into this repo (which I'll happily do, already [wrote the logic for that once](https://github.com/yoshuawuyts/crossgen).

Is this something you'd like to take a stab at?

**Comment by pierd** [comment]
I'll give it a go

**Comment by pierd** [comment]
It works! https://pierd.github.io/book/

To make it work:
1. [Generate a token with `public_repo`](https://github.com/settings/tokens/new).
2. Set it as `GITHUB_TOKEN` environment variable in [travis-ci `datrs/book` settings](https://travis-ci.org/datrs/book/settings).
3. Commit something to master to trigger a build.

**Comment by yoshuawuyts** [comment]
Yay, done! https://datprotocol.github.io/book/

**Comment by pierd** [comment]
Hmm. Are you sure? https://datprotocol.github.io/book/ works for me.
